### ISSUE TITLE
Limit proposal title to 100 characters and add limit to placehold

### ISSUE THREAD

**Issue by jamesholston** [peer/doc#120]
-- Limit proposal title to 100 characters 
-- Add "(máximo 100 caracteres)" after title instruction as placehold:

Escreva Aqui o Título da Proposta (máximo 100 caracteres)

**Comment by mitar** [comment]
I would propose that we use [snackbar notification](https://github.com/peer/doc/blob/devel/client/snackbar.js) for this. So as the person types, we should be checking the length and if it gets longer or equal to 100 characters, we issue a warning message "Please keep title shorter than 100 characters." Every time a title is changed, if it is longer or equal to 100 characters, we should issue this warning.

I would not make this a hard limit though, because this might be hard (and took more time) to implement.

This should be done on the master branch so that we can quickly deploy it.

**Comment by mitar** [comment]
Let's try for now:
* "Your title should be brief, a maximum of 100 characters." -> "Seu título deve ser breve, máximo de 100 caracteres."

If you see that it works larger, then try:
* "Seu título deve ser breve, máximo de 100 caracteres, e o texto do seu documento deve ser adicionado no espaço abaixo do título." -> "Your title should be brief, a maximum of 100 characters, and the text of your document should be added in the space below the title."

I think that the second text will be too long for the snackbar warning.

**Comment by mitar** [comment]
This has been done and merged. Rebuilding images now and then it can be deployed.
