### ISSUE TITLE
Change title limit to 80 characters instead of 100

### ISSUE THREAD

**Issue by jamesholston** [peer/doc#125]
The waring about title length works well.  However, I think that 100 characters is too long because it produces a title of two lines both in the PeerDoc document and in the AppCivist title.  It's too long.

![screen shot 2018-06-29 at 12 57 58 am](https://user-images.githubusercontent.com/5572598/42072610-c8f58524-7b37-11e8-8cb1-c79a7eebe1a0.png)

A title of 80 characters goes to the end of one line and seems right:

![screen shot 2018-06-29 at 1 06 31 am](https://user-images.githubusercontent.com/5572598/42072774-cc916346-7b38-11e8-8716-adf0fc7ac210.png)

**Comment by mitar** [comment]
This really depends on the window width, and also font size. I do not think we can really go and try to get one line. Because also characters are of different widths. For example 80 "m" characters is much wider than 80 "i" characters.

I think the main purpose here is to warn the user that they are doing something wrong. I think we achieve this. You cannot really put whole proposal into 100 characters.

**Comment by mitar** [comment]
I tested this a bit, it really changes depending on the window size and everything else. We cannot aim for one line, but just be approximate. I think 100 is a reasonable number and it is clear that it is approximate.
