### ISSUE TITLE
Make content read-only (but commentable)

### ISSUE THREAD

**Issue by mitar** [peer/doc#36]
Currently, all documents are editable by anyone. We should change this in the following way:
* When you click that a new document is to be created, it is created in DRAFTING state.
* When in DRAFTING state, anyone who knows the URL (document ID) can edit it, but if you do not know the URL you cannot edit it.
* There should be a button on the draft to publish it, making a document into PUBLISHED state.
  * Clicking on a button redirects to `/document/publish/<documentId>` page with confirmation form.
  * For now only a message that publishing will prevent document from being edited. And if they want to do so.
* All documents in PUBLISHED state are listed on the front page (list of documents).
* When a document is published, editing of content is not possible anymore, but anyone can continue to create comments and resolve them.
* Documents already have two fields for this: `publishedBy` and `publishedAt`. When a document is published these two fields are set and this makes its state to PUBLISHED. If they are null document is in DRAFTING state.

**Comment by cdparra** [comment]
About the status: one common feature of some participatory processes we have worked on with AppCivist is that they go through different stages, in which their proposals can go from being in DRAFTING mode, to PUBLISHED while waiting for assessments/reviews, and then to DRAFTING mode again to incorporate feedback. 

Therefore, I suggest you consider the possibility of having the status as an `attribute` of the peerdoc, because then you can go back and forth between different statuses. 

The question would be then: who can change status?. Authors should probably have that possibility, but then you need authentication, and until we have that fully developed, I think it would be good to follow Etherpad's logic: adding to the peerdoc two different hash ids (1) 1 is the one you use to build the editing URL, (2) and the other is for read only. For example, [this pad](https://etherpad.appcivist.org/p/asdfasdfasdfasdfasdfasdf) has a [read only url that starts with `r.`](https://etherpad.appcivist.org/p/r.e7df1dd00dac690ba6061549e2921596) 

Then, if I know the editing URL, I can change the status and edit. If I know only the read only URL, I won't be able to edit even if it is in DRAFTING mode.

**Comment by mitar** [comment]
Hm, we have not planned to have this for PeerDoc. The approach we discussed here with James is that real-time editing is only during the first drafting stage. After it becomes public you cannot then edit it anymore (even if you are author) directly, but only through "pull requests". We do not have pull requests implemented yet.

I do not think we will allow people to go back. They can make a copy of the proposal and make a new proposal for now.

So, what you are saying is not how we imagined the overall process. Maybe we can discuss it with James and Rodrigo.

**Comment by mitar** [comment]
So I think "incorporate feedback" stage will have to be integrated differently with AppCivist. The question is though if you want to use PeerDoc as a replacement for Etherpad in all cases in AppCivist, or just now for this project.

**Comment by mitar** [comment]
cc @subjective

**Comment by voluntadpear** [comment]
> There should be a button on the draft to publish it, making a document into PUBLISHED state.
Clicking on a button redirects to `/document/publish/<documentId>` page with confirmation form.
For now only a message that publishing will prevent document from being edited. And if they want to do so.

Why should it redirect you to a new URL, couldn't we implement it so that when you click the button a confirmation pop-up is opened, like when inserting a link or comment?

**Comment by subjective** [comment]
I think it's sufficient to go from "drafting" to "published" state only once.  This approach is easier to understand and makes the process more accountable.  After a document is published, it will still be editable through proposals.  This approach accommodates the AppCivist use cases: the only difference is that instead of allowing real-time editing directly on the "master" document, we would create a proposal ("branch") and allow real-time editing on the proposal.  The proposal could then be merged either by voting or by facilitator approval, depending on the configuration of the document.  The UI can display how each proposal was merged (by voting or by facilitator approval).

If we allow real-time editing directly on the published document, we need some way to display those status changes on the UI.  Otherwise, we would undermine the point of having proposals in the first place.  This approach might give slightly more flexibility to facilitators, but would make the process significantly more complicated and potentially less accountable to users.

**Comment by cdparra** [comment]
Agree with @subjective and @mitar. AppCivist cases can be implemented through subsequent proposals and pull-requests of these proposals into the main document.

**Comment by mitar** [comment]
We should discuss this with James because he made some good points why we should allow editing. For example, in the initial phase, authors might want to float the document around, get comments from people, update the draft, before it becomes full proposal to go into thematic working groups.

We would need for that permissions through, and also probably private and public comments. Also way to show changes since last time user was around.
